targetScope = 'resourceGroup'

param location string
param workloadName string
param deploymentStamp string
param deployFoundry bool
param deployChatModel bool
param deployEmbeddingModel bool
param deployIdentity bool
param deployStorage bool
param deploySearch bool
param deployObservability bool
param deployPrivateNetwork bool
param storageSku string
param searchSku string
param searchReplicaCount int
param logRetentionDays int
param chatModelName string
param chatModelVersion string
param chatModelSku string
param chatModelCapacity int
param embeddingModelName string
param embeddingModelVersion string
param embeddingModelSku string
param embeddingModelCapacity int
param tags object

var suffix = take(toLower(deploymentStamp), 6)
var normalizedName = take(toLower(replace(workloadName, '-', '')), 12)
var identityName = 'id-${workloadName}-${suffix}'
var foundryName = 'aif-${workloadName}-${suffix}'
var projectName = 'proj-${workloadName}'
var storageName = take('st${normalizedName}${suffix}', 24)
var searchName = take('srch-${workloadName}-${suffix}', 60)
var logName = 'log-${workloadName}-${suffix}'
var insightsName = 'appi-${workloadName}-${suffix}'
var networkName = 'vnet-${workloadName}-${suffix}'

resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = if (deployIdentity) {
  name: identityName
  location: location
  tags: tags
}

resource foundryAccount 'Microsoft.CognitiveServices/accounts@2025-06-01' = if (deployFoundry) {
  name: foundryName
  location: location
  kind: 'AIServices'
  sku: {
    name: 'S0'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    allowProjectManagement: true
    customSubDomainName: foundryName
    disableLocalAuth: true
    publicNetworkAccess: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    // POC public access remains Entra-only because local authentication is disabled.
    networkAcls: {
      defaultAction: deployPrivateNetwork ? 'Deny' : 'Allow'
    }
  }
  tags: tags
}

resource foundryProject 'Microsoft.CognitiveServices/accounts/projects@2025-06-01' = if (deployFoundry) {
  parent: foundryAccount
  name: projectName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    displayName: workloadName
    description: 'Generated by the governed AI application launchpad.'
  }
  tags: tags
}

resource chatModel 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = if (deployFoundry && deployChatModel) {
  parent: foundryAccount
  name: chatModelName
  dependsOn: [
    foundryProject
  ]
  sku: {
    name: chatModelSku
    capacity: chatModelCapacity
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: chatModelName
      version: chatModelVersion
    }
    raiPolicyName: 'Microsoft.DefaultV2'
    versionUpgradeOption: 'OnceNewDefaultVersionAvailable'
  }
}

resource embeddingModel 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = if (deployFoundry && deployEmbeddingModel) {
  parent: foundryAccount
  name: embeddingModelName
  dependsOn: [
    chatModel
  ]
  sku: {
    name: embeddingModelSku
    capacity: embeddingModelCapacity
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: embeddingModelName
      version: embeddingModelVersion
    }
    raiPolicyName: 'Microsoft.DefaultV2'
    versionUpgradeOption: 'OnceNewDefaultVersionAvailable'
  }
}

resource storage 'Microsoft.Storage/storageAccounts@2023-05-01' = if (deployStorage) {
  name: storageName
  location: location
  kind: 'StorageV2'
  sku: {
    name: storageSku
  }
  properties: {
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    defaultToOAuthAuthentication: true
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    supportsHttpsTrafficOnly: true
    // POC packages allow public routing but retain OAuth-only data-plane access.
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: deployPrivateNetwork ? 'Deny' : 'Allow'
      ipRules: []
      virtualNetworkRules: []
    }
  }
  tags: tags
}

resource search 'Microsoft.Search/searchServices@2024-03-01-preview' = if (deploySearch) {
  name: searchName
  location: location
  sku: {
    name: searchSku
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    disableLocalAuth: true
    hostingMode: 'default'
    publicNetworkAccess: deployPrivateNetwork ? 'disabled' : 'enabled'
    networkRuleSet: {
      ipRules: []
    }
    replicaCount: searchReplicaCount
    semanticSearch: 'free'
  }
  tags: tags
}

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = if (deployObservability) {
  name: logName
  location: location
  properties: {
    retentionInDays: logRetentionDays
    publicNetworkAccessForIngestion: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    publicNetworkAccessForQuery: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    sku: {
      name: 'PerGB2018'
    }
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
  }
  tags: tags
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = if (deployObservability) {
  name: insightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    DisableLocalAuth: true
    publicNetworkAccessForIngestion: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    publicNetworkAccessForQuery: deployPrivateNetwork ? 'Disabled' : 'Enabled'
    WorkspaceResourceId: logAnalytics.id
  }
  tags: tags
}

resource virtualNetwork 'Microsoft.Network/virtualNetworks@2024-05-01' = if (deployPrivateNetwork) {
  name: networkName
  location: location
  properties: {
    addressSpace: {
      addressPrefixes: [
        '10.42.0.0/16'
      ]
    }
    subnets: [
      {
        name: 'private-endpoints'
        properties: {
          addressPrefix: '10.42.1.0/24'
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
    ]
  }
  tags: tags
}

output deployment object = {
  resourceGroupName: resourceGroup().name
  identityName: deployIdentity ? identity.name : ''
  identityResourceId: deployIdentity ? identity.id : ''
  identityClientId: deployIdentity ? identity.properties.clientId : ''
  identityPrincipalId: deployIdentity ? identity.properties.principalId : ''
  foundryAccountName: deployFoundry ? foundryAccount.name : ''
  foundryAccountResourceId: deployFoundry ? foundryAccount.id : ''
  foundryProjectName: deployFoundry ? projectName : ''
  foundryProjectResourceId: deployFoundry ? foundryProject.id : ''
  foundryProjectEndpoint: deployFoundry ? 'https://${foundryName}.services.ai.azure.com/api/projects/${projectName}' : ''
  chatModelDeployment: deployChatModel ? chatModelName : ''
  chatModelResourceId: deployChatModel ? chatModel.id : ''
  embeddingModelDeployment: deployEmbeddingModel ? embeddingModelName : ''
  embeddingModelResourceId: deployEmbeddingModel ? embeddingModel.id : ''
  storageAccountName: deployStorage ? storage.name : ''
  storageResourceId: deployStorage ? storage.id : ''
  storageBlobEndpoint: deployStorage ? 'https://${storageName}.blob.${environment().suffixes.storage}' : ''
  searchServiceName: deploySearch ? search.name : ''
  searchResourceId: deploySearch ? search.id : ''
  searchEndpoint: deploySearch ? 'https://${searchName}.search.windows.net' : ''
  applicationInsightsName: deployObservability ? applicationInsights.name : ''
  applicationInsightsResourceId: deployObservability ? applicationInsights.id : ''
  virtualNetworkName: deployPrivateNetwork ? virtualNetwork.name : ''
  virtualNetworkResourceId: deployPrivateNetwork ? virtualNetwork.id : ''
}
