import { useState } from 'react'
import './council-workspace.css'

type Decision = 'Approve' | 'Approve with conditions' | 'Request changes' | 'Decline'
type Application = {
  id:string; name:string; owner:string; unit:string; submitted:string; risk:'Moderate'|'High'|'Restricted'; score:number; stage:string; sla:string; summary:string
}

const applications:Application[] = [
  {id:'AI-2026-0157',name:'Clinical Document Assistant',owner:'Priya Shah',unit:'MedTech',submitted:'Sep 8, 2026',risk:'Restricted',score:81,stage:'Council decision',sla:'Due today',summary:'Draft and summarize clinical evaluation documents using approved study evidence.'},
  {id:'AI-2026-0142',name:'Commercial Content Assistant',owner:'Nathan Biyani',unit:'Innovative Medicine',submitted:'Sep 6, 2026',risk:'Moderate',score:46,stage:'Council decision',sla:'1 day left',summary:'Create compliant first drafts of commercial content for human medical and legal review.'},
  {id:'AI-2026-0139',name:'Complaint Triage Copilot',owner:'Alicia Gomez',unit:'MedTech',submitted:'Sep 5, 2026',risk:'High',score:69,stage:'Specialist review',sla:'2 days left',summary:'Classify incoming product complaints and recommend routing for post-market surveillance teams.'},
  {id:'AI-2026-0128',name:'Supplier Risk Signal Agent',owner:'Marcus Chen',unit:'Enterprise',submitted:'Sep 2, 2026',risk:'High',score:63,stage:'Evidence incomplete',sla:'Paused',summary:'Monitor approved supplier information and surface emerging operational risk signals.'},
]

function Tone({children,tone}:{children:React.ReactNode;tone:string}){return <span className={`council-pill ${tone.toLowerCase().replace(/ /g,'-')}`}>{children}</span>}

function ReviewDetail({app,back,complete}:{app:Application;back:()=>void;complete:(decision:Decision)=>void}){
  const [tab,setTab]=useState<'Overview'|'Risk & controls'|'Evidence'|'Reviews'>('Overview')
  const [decision,setDecision]=useState<Decision>('Approve with conditions')
  const [rationale,setRationale]=useState('Approval is contingent on human review before regulated use and completion of production validation evidence.')
  const controls=['Human review before any regulated output is used','Prompt, output, citation, and action audit logging','Use only council-approved models and governed data connections','Complete production validation before go-live']
  return <main className="council-review">
    <div className="review-nav"><button onClick={back}>← Review queue</button><span>{app.id}</span><div><button className="council-secondary">Save notes</button><button className="council-primary" onClick={()=>complete(decision)}>Record decision</button></div></div>
    <section className="review-title"><div><span>GENAI COUNCIL REVIEW</span><h1>{app.name}</h1><p>{app.summary}</p></div><div className="review-title-meta"><Tone tone={app.risk}>{app.risk} risk · {app.score}/100</Tone><span>{app.sla}</span></div></section>
    <div className="review-layout"><section className="review-main council-card"><div className="review-tabs">{(['Overview','Risk & controls','Evidence','Reviews'] as const).map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}{item==='Evidence'&&<b>1</b>}</button>)}</div>
      {tab==='Overview'&&<div className="tab-content"><section><h2>Application overview</h2><div className="facts"><span><small>Business owner</small><strong>{app.owner}</strong></span><span><small>Business unit</small><strong>{app.unit}</strong></span><span><small>Primary audience</small><strong>J&J employees</strong></span><span><small>Lifecycle stage</small><strong>Pilot</strong></span></div></section><section><h2>Proposed use</h2><p>{app.summary} The application retrieves approved internal evidence, generates cited drafts, and requires a qualified reviewer to accept or revise all output.</p></section><section><h2>AI and data scope</h2><div className="scope-grid"><article><b>✦</b><span><strong>Generative AI</strong><small>Summarization and grounded drafting</small></span></article><article><b>▤</b><span><strong>Regulated data</strong><small>Clinical and quality documentation</small></span></article><article><b>⌕</b><span><strong>Grounded retrieval</strong><small>Approved enterprise knowledge only</small></span></article><article><b>◉</b><span><strong>Assistive autonomy</strong><small>No autonomous business actions</small></span></article></div></section><section className="council-callout"><b>i</b><span><strong>Why council review is required</strong><small>Regulated data and potential product-quality impact trigger GenAI Council oversight and MedTech Quality concurrence.</small></span></section></div>}
      {tab==='Risk & controls'&&<div className="tab-content"><section><h2>Risk assessment</h2>{[['Data sensitivity',88],['Business impact',74],['AI autonomy',36],['External exposure',12],['Regulatory relevance',91]].map(([name,value])=><div className="risk-row" key={name}><span>{name}</span><div><i style={{width:`${value}%`}}/></div><b>{value}</b></div>)}</section><section><h2>Required controls</h2><div className="control-list">{controls.map(control=><label key={control}><input type="checkbox" defaultChecked/><span><strong>{control}</strong><small>Mapped to enterprise GenAI control framework</small></span></label>)}</div></section></div>}
      {tab==='Evidence'&&<div className="tab-content"><section><h2>Evidence package</h2><div className="evidence-list">{[['AI impact assessment','Complete','Sep 8'],['Privacy assessment','Complete','Sep 8'],['Security architecture review','Complete','Sep 9'],['Production validation plan','Action required','Not provided'],['Data-flow diagram','Complete','Sep 7']].map(item=><article key={item[0]}><b>▧</b><span><strong>{item[0]}</strong><small>{item[2]}</small></span><Tone tone={item[1]}>{item[1]}</Tone><button>View</button></article>)}</div></section></div>}
      {tab==='Reviews'&&<div className="tab-content"><section><h2>Specialist recommendations</h2><div className="reviewer-list">{[['Privacy','Approved','No unresolved privacy concerns'],['Information Security','Approved with conditions','Private endpoints and managed identity required'],['MedTech Quality','Approved with conditions','Validation evidence required before production'],['Responsible AI','Approved','Human oversight is appropriately designed']].map(item=><article key={item[0]}><i>{item[0].split(' ').map(x=>x[0]).join('')}</i><span><strong>{item[0]}</strong><small>{item[2]}</small></span><Tone tone={item[1]}>{item[1]}</Tone></article>)}</div></section></div>}
    </section>
    <aside className="decision-panel council-card"><div><span>COUNCIL DECISION</span><h2>Record determination</h2><p>The decision, rationale, and conditions become part of the permanent governance record.</p></div><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value as Decision)}><option>Approve</option><option>Approve with conditions</option><option>Request changes</option><option>Decline</option></select></label><label>Rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)}/></label><section><h3>Conditions attached</h3>{controls.slice(0,3).map(control=><label key={control}><input type="checkbox" defaultChecked/><span>{control}</span></label>)}<button>+ Add condition</button></section><label>Next review<select><option>Before production launch</option><option>In 90 days</option><option>Annual review</option><option>No scheduled review</option></select></label><div className="decision-ready"><b>✓</b><span><strong>Quorum satisfied</strong><small>5 of 7 voting members participated</small></span></div><button className="council-primary wide" disabled={!rationale.trim()} onClick={()=>complete(decision)}>Record {decision.toLowerCase()}</button></aside>
    </div>
  </main>
}

export default function CouncilWorkspace(){
  const [selected,setSelected]=useState<Application|null>(null)
  const [completed,setCompleted]=useState<{app:Application;decision:Decision}|null>(null)
  if(completed)return <main className="decision-complete"><div>✓</div><span>DECISION RECORDED</span><h1>{completed.decision}</h1><p>{completed.app.name} · {completed.app.id}</p><section><span>Governance record<strong>GR-2026-0841</strong></span><span>Applicant notification<strong>Queued</strong></span><span>Next checkpoint<strong>Before production</strong></span></section><button className="council-primary" onClick={()=>{setCompleted(null);setSelected(null)}}>Return to review queue</button></main>
  if(selected)return <ReviewDetail app={selected} back={()=>setSelected(null)} complete={decision=>setCompleted({app:selected,decision})}/>
  return <main className="council-page"><section className="council-welcome"><div><p>GENAI COUNCIL WORKSPACE</p><h1>Application oversight</h1><span>Review risk, evidence, and specialist recommendations before making accountable decisions.</span></div><button className="council-secondary">Export council pack</button></section>
    <section className="council-stats">{[['7','Awaiting decision','2 due today','urgent'],['3','Evidence gaps','Blocking review','warning'],['12','Decided this month','9 approved','success'],['4.2 days','Median cycle time','↓ 18% this quarter','neutral']].map(item=><article key={item[1]}><span>{item[0]}</span><div><strong>{item[1]}</strong><small>{item[2]}</small></div><i className={item[3]}/></article>)}</section>
    <section className="council-grid"><div className="council-card queue"><div className="queue-head"><div><h2>Decision queue</h2><p>Applications requiring council or delegated approval.</p></div><div className="queue-filters"><button className="active">My agenda</button><button>All reviews</button><button>Evidence gaps</button></div></div><div className="queue-table"><div className="queue-row queue-labels"><span>Application</span><span>Risk</span><span>Review stage</span><span>SLA</span><span/></div>{applications.map(app=><button className="queue-row" onClick={()=>setSelected(app)} key={app.id}><span><strong>{app.name}</strong><small>{app.id} · {app.owner} · {app.unit}</small></span><span><Tone tone={app.risk}>{app.risk} · {app.score}</Tone></span><span>{app.stage}</span><span className={app.sla==='Due today'?'due':''}>{app.sla}</span><span>→</span></button>)}</div></div><aside><section className="council-card agenda"><div><span>WEDNESDAY · SEP 9</span><h2>Today’s council agenda</h2></div>{[['09:30','Clinical Document Assistant','Decision'],['09:50','Commercial Content Assistant','Decision'],['10:10','Control framework update','Policy']].map(item=><article key={item[0]}><b>{item[0]}</b><span><strong>{item[1]}</strong><small>{item[2]}</small></span></article>)}<button>Open meeting pack →</button></section><section className="council-card health"><h3>Portfolio risk</h3><div><span><i className="low" style={{width:'42%'}}/>Low · 42%</span><span><i className="moderate" style={{width:'31%'}}/>Moderate · 31%</span><span><i className="high" style={{width:'21%'}}/>High · 21%</span><span><i className="restricted" style={{width:'6%'}}/>Restricted · 6%</span></div><small>Across 84 active AI applications</small></section></aside></section>
  </main>
}
