import { useEffect, useMemo, useState } from 'react'
import './prototype.css'
import SolutionBuilder from './SolutionBuilder'
import CouncilWorkspace from './CouncilWorkspace'
import { getBicepPackage } from './api'

type Answer = 'yes' | 'no' | ''
type RiskLevel = 'Low' | 'Moderate' | 'High' | 'Restricted'
type View = 'dashboard' | 'intake' | 'submitted' | 'solution' | 'council'
const portalViewKey='launchpad.portal-view'
const portalViews=new Set<View>(['dashboard','intake','submitted','solution','council'])

function restoredPortalView():View{
  try{
    const value=sessionStorage.getItem(portalViewKey) as View|null
    return value&&portalViews.has(value)?value:'dashboard'
  }catch{return'dashboard'}
}
type Form = {
  name:string; summary:string; unit:string; owner:string; audience:string; stage:string
  personal:Answer; health:Answer; employee:Answer; confidential:Answer; regulated:Answer
  identifiable:Answer; modelTraining:Answer; externalData:Answer; crossBorder:Answer
  capabilities:string[]; autonomy:number; publicFacing:Answer; safety:Answer; quality:Answer
  decisions:Answer; humanReview:Answer; audit:Answer
}
type Risk = {level:RiskLevel;score:number;dimensions:{name:string;value:number}[];reasons:string[];reviewers:string[];controls:string[]}
const initial:Form={name:'',summary:'',unit:'',owner:'',audience:'',stage:'',personal:'',health:'',employee:'',confidential:'',regulated:'',identifiable:'',modelTraining:'',externalData:'',crossBorder:'',capabilities:[],autonomy:1,publicFacing:'',safety:'',quality:'',decisions:'',humanReview:'',audit:''}
const stepNames=['Application basics','Data & privacy','AI capabilities','Impact & controls','Review & submit']
const apps=[
  ['Commercial Content Assistant','AI-2026-0142','In review','Moderate','58%','Sep 8, 2026'],
  ['Quality Event Summarizer','AI-2026-0118','Approved','High','100%','Sep 5, 2026'],
  ['Supply Chain Knowledge Search','AI-2026-0097','Draft','Low','32%','Aug 29, 2026'],
]
function calculate(f:Form):Risk{
  let data=0,impact=0,exposure=0,regulatory=0
  const reasons:string[]=[],controls:string[]=[]
  const reviewers=new Set(['Business owner','AI Governance'])
  if(f.personal==='yes'){data+=35;reviewers.add('Privacy');reasons.push('Personal information will be processed')}
  if(f.health==='yes'){data+=55;regulatory+=40;reviewers.add('Privacy');reviewers.add('Health Care Compliance');reasons.push('Patient or health information is in scope')}
  if(f.employee==='yes'){data+=25;reviewers.add('Privacy');reasons.push('Employee information will be processed')}
  if(f.confidential==='yes'){data+=25;reviewers.add('Information Security');reasons.push('Confidential J&J information will be used')}
  if(f.regulated==='yes'){data+=30;regulatory+=45;reviewers.add('MedTech Quality');reasons.push('Regulated quality or clinical data is in scope')}
  if(f.identifiable==='yes'&&(f.personal==='yes'||f.health==='yes')){data+=20;reasons.push('Sensitive information may be directly identifiable')}
  if(f.modelTraining==='yes'){data+=25;reviewers.add('Privacy');reviewers.add('Responsible AI');controls.push('Define training-data use, retention, and deletion controls')}
  if(f.externalData==='yes'){exposure+=45;reviewers.add('Information Security');controls.push('Document data residency and transfer safeguards')}
  if(f.crossBorder==='yes'){exposure+=25;reviewers.add('Privacy');controls.push('Complete cross-border data transfer assessment')}
  if(f.publicFacing==='yes'){exposure+=45;reviewers.add('Responsible AI');reasons.push('The experience will be externally accessible')}
  if(f.safety==='yes'){impact+=75;regulatory+=50;reviewers.add('MedTech Quality');reasons.push('Incorrect output could affect patient safety')}
  if(f.quality==='yes'){impact+=50;regulatory+=40;reviewers.add('MedTech Quality');reasons.push('Output may influence product quality')}
  if(f.decisions==='yes'){impact+=40;reviewers.add('Responsible AI');reasons.push('AI may influence a consequential decision')}
  if(f.autonomy>=4){reviewers.add('Enterprise Architecture');reviewers.add('Responsible AI');reasons.push('The application can act in connected systems')}
  if(f.capabilities.includes('Execute actions'))reviewers.add('Information Security')
  if(f.humanReview==='yes')impact=Math.max(0,impact-15)
  if(f.humanReview==='no'&&f.autonomy>=3)controls.push('Add human review before consequential actions')
  if(f.audit==='no')controls.push('Enable prompt, output, and action audit logging')
  const dimensions=[{name:'Data sensitivity',value:Math.min(100,data)},{name:'AI autonomy',value:f.autonomy*18},{name:'Business impact',value:Math.min(100,impact)},{name:'External exposure',value:Math.min(100,exposure)},{name:'Regulatory relevance',value:Math.min(100,regulatory)}]
  const max=Math.max(...dimensions.map(d=>d.value)),avg=dimensions.reduce((a,d)=>a+d.value,0)/5
  const score=Math.round(max*.65+avg*.35)
  const level:RiskLevel=score>=75?'Restricted':score>=50?'High':score>=22?'Moderate':'Low'
  if(!reasons.length)reasons.push('No elevated risk indicators selected yet')
  return{level,score,dimensions,reasons,reviewers:[...reviewers],controls}
}
function Icon({name}:{name:string}){const p:Record<string,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,plus:<path d="M12 5v14M5 12h14"/>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/><path d="m9 12 2 2 4-4"/></>,arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>,back:<><path d="M19 12H5M11 18l-6-6 6-6"/></>,check:<path d="m5 12 4 4L19 6"/>,save:<><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2"/><path d="M17 21v-8H7v8M7 3v5h8"/></>,info:<><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></>,data:<><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 1.7 4 3 9 3s9-1.3 9-3V5M3 12c0 1.7 4 3 9 3s9-1.3 9-3"/></>,spark:<><path d="m12 3-1.7 4.3L6 9l4.3 1.7L12 15l1.7-4.3L18 9l-4.3-1.7L12 3z"/><path d="m5 16-.8 2.2L2 19l2.2.8L5 22l.8-2.2L8 19l-2.2-.8L5 16z"/></>};return <svg className="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function Pill({text,tone}:{text:string;tone:string}){return <span className={`pill ${tone.toLowerCase().replace(' ','-')}`}>{text}</span>}
function Header({home,council,active}:{home:()=>void;council:()=>void;active:'developer'|'council'}){return <header><button className="brand" onClick={home}><b>J&J</b><span><strong>AI Launchpad</strong><small>Governed AI delivery</small></span></button><nav><button className={active==='developer'?'active':''} onClick={home}><Icon name="grid"/>My applications</button><button className={active==='council'?'active':''} onClick={council}><Icon name="shield"/>Council workspace</button></nav><div className="profile"><span>{active==='council'?'GC':'NB'}</span><div><strong>{active==='council'?'GenAI Council':'Nathan Biyani'}</strong><small>{active==='council'?'Council member':'Requester'}</small></div></div></header>}
function ConfigurationDashboard({start,configure}:{start:()=>void;configure:()=>void}){return <main className="page"><section className="welcome"><div><p className="eyebrow">AI APPLICATION WORKSPACE</p><h1>Good morning, Nathan</h1><p>Request, govern, and launch trusted AI solutions from one place.</p></div><button className="primary" onClick={start}><Icon name="plus"/>New AI application</button></section><section className="stats">{[['3','My applications','2 active','blue'],['1','Awaiting action','Review requested','amber'],['1','Approved','Ready to configure','green'],['82%','Governance complete','Across active requests','violet']].map(x=><article key={x[1]}><i className={x[3]}><Icon name={x[1]==='Approved'?'check':x[1]==='Governance complete'?'shield':'info'}/></i><div><b>{x[0]}</b><span>{x[1]}</span></div><small>{x[2]}</small></article>)}</section><section className="dash-grid"><div className="card applications"><div className="card-title"><div><h2>My AI applications</h2><p>Track requests from idea through approval.</p></div><button>View all <Icon name="arrow"/></button></div><div className="table-scroll"><table><thead><tr><th>Application</th><th>Status</th><th>Risk</th><th>Progress</th><th>Updated</th><th/></tr></thead><tbody>{apps.map(a=><tr key={a[1]} className={a[2]==='Approved'?'approved-row':''} onClick={()=>a[2]==='Approved'&&configure()}><td><b>{a[0]}</b><small>{a[1]} · N. Biyani</small></td><td><Pill text={a[2]} tone={a[2]}/></td><td><Pill text={a[3]} tone={a[3]}/></td><td><div className="bar"><i style={{width:a[4]}}/></div><small>{a[4]}</small></td><td>{a[5]}</td><td>{a[2]==='Approved'?<button className="configure-link" onClick={configure}>Configure →</button>:'›'}</td></tr>)}</tbody></table></div></div><aside className="card start"><div className="graphic"><Icon name="spark"/></div><p className="eyebrow">GUIDED EXPERIENCE</p><h2>Have an AI idea?</h2><p>Describe your use case in plain language. We’ll identify the governance path and teams needed to launch safely.</p><button className="primary wide" onClick={start}>Start a request <Icon name="arrow"/></button><small>◷ Most requests take 8–12 minutes</small></aside></section><section className="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>One request. One transparent path.</h2></div>{['Tell us about your idea','See your risk profile','Get routed for review','Configure & build'].map((x,i)=><article key={x}><b>{i+1}</b><div><strong>{x}</strong><p>{['Answer guided questions.','See triggers as you answer.','We coordinate required teams.','Choose approved components.'][i]}</p></div></article>)}</section></main>}
function YesNo({label,help,value,onChange}:{label:string;help?:string;value:Answer;onChange:(a:Answer)=>void}){return <div className="question"><div><label>{label}</label>{help&&<p>{help}</p>}</div><div className="segments"><button className={value==='yes'?'on':''} onClick={()=>onChange('yes')}>Yes</button><button className={value==='no'?'on':''} onClick={()=>onChange('no')}>No</button><button className={value===''?'on':''} onClick={()=>onChange('')}>Not sure</button></div></div>}
function Choice({title,sub,selected,toggle}:{title:string;sub?:string;selected:boolean;toggle:()=>void}){return <button className={`choice ${selected?'selected':''}`} onClick={toggle}><i>{selected&&<Icon name="check"/>}</i><span><b>{title}</b>{sub&&<small>{sub}</small>}</span></button>}
type Props={form:Form;set:<K extends keyof Form>(k:K,v:Form[K])=>void}
function Heading({step,title,sub,icon}:{step:number;title:string;sub:string;icon:string}){return <div className="step-head"><i><Icon name={icon}/></i><div><p>STEP {step+1} OF 5</p><h2>{title}</h2><span>{sub}</span></div></div>}
function Basics({form:f,set}:Props){return <><Heading step={0} icon="spark" title="Tell us about your AI application" sub="Start with what you know. You can save a draft and return at any time."/><div className="form-grid"><Field label="Application name *" wide><input value={f.name} onChange={e=>set('name',e.target.value)} placeholder="e.g., Clinical Document Assistant"/><small>Use a working title—you can change it later.</small></Field><Field label="What problem are you trying to solve? *" wide><textarea value={f.summary} onChange={e=>set('summary',e.target.value)} placeholder="Describe the business need, who it helps, and the outcome you expect..."/><small className="count">{f.summary.length} / 500</small></Field><Field label="Business unit *"><select value={f.unit} onChange={e=>set('unit',e.target.value)}><option value="">Select business unit</option><option>MedTech</option><option>Innovative Medicine</option><option>Enterprise</option></select></Field><Field label="Business owner *"><input value={f.owner} onChange={e=>set('owner',e.target.value)} placeholder="Search by name or email"/></Field><Field label="Primary audience"><select value={f.audience} onChange={e=>set('audience',e.target.value)}><option value="">Select audience</option><option>J&J employees</option><option>Health care professionals</option><option>Patients or consumers</option><option>Public</option></select></Field><Field label="Current stage"><select value={f.stage} onChange={e=>set('stage',e.target.value)}><option value="">Select stage</option><option>Idea / discovery</option><option>Proof of concept</option><option>Pilot</option><option>Production</option></select></Field></div></>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <div className={`field ${wide?'wide':''}`}><label>{label}</label>{children}</div>}
function Data({form:f,set}:Props){return <><Heading step={1} icon="data" title="Data & privacy" sub="Describe the data characteristics that affect risk. Specific sources are selected after approval."/><div className="question-group"><h3>Data classification</h3><p>What categories of information could the application access or process?</p></div><div className="questions"><YesNo label="Will the application process personal information?" help="Information that identifies or could identify an individual." value={f.personal} onChange={v=>set('personal',v)}/><YesNo label="Will it use patient or health information?" help="Includes clinical, diagnosis, treatment, or medical device data." value={f.health} onChange={v=>set('health',v)}/><YesNo label="Will it process employee or workforce information?" value={f.employee} onChange={v=>set('employee',v)}/><YesNo label="Will it use confidential J&J information or intellectual property?" value={f.confidential} onChange={v=>set('confidential',v)}/><YesNo label="Will it use regulated quality, clinical, or safety data?" value={f.regulated} onChange={v=>set('regulated',v)}/></div><div className="question-group"><h3>Data handling</h3><p>How will sensitive information be identified, reused, and transferred?</p></div><div className="questions"><YesNo label="Could personal or health information be directly identifiable?" help="For example: names, IDs, contact details, or linkable records." value={f.identifiable} onChange={v=>set('identifiable',v)}/><YesNo label="Will application data be used to train or fine-tune a model?" value={f.modelTraining} onChange={v=>set('modelTraining',v)}/><YesNo label="Will data be processed outside J&J-controlled systems?" value={f.externalData} onChange={v=>set('externalData',v)}/><YesNo label="Could data cross national or regional boundaries?" value={f.crossBorder} onChange={v=>set('crossBorder',v)}/></div><div className="deferred-note"><Icon name="info"/><div><strong>Data connections come later</strong><span>After initial approval, you’ll choose specific knowledge sources, systems, access roles, and retention settings during solution configuration.</span></div></div></>}
function Capabilities({form:f,set}:Props){const caps=[['Search & answer','Find and explain information'],['Summarize','Condense documents or records'],['Generate content','Create text, images, or code'],['Recommend actions','Suggest decisions or next steps'],['Execute actions','Call tools or update systems'],['Multi-agent workflow','Coordinate specialized agents']];return <><Heading step={2} icon="spark" title="AI capabilities" sub="What should the application be able to do?"/><Field label="Select all proposed capabilities"><div className="choices two">{caps.map(x=><Choice key={x[0]} title={x[0]} sub={x[1]} selected={f.capabilities.includes(x[0])} toggle={()=>set('capabilities',f.capabilities.includes(x[0])?f.capabilities.filter(v=>v!==x[0]):[...f.capabilities,x[0]])}/>)}</div></Field><div className="autonomy"><label>Level of autonomy</label><p>How independently can the application operate?</p><div><b>{['','Informational','Assistive','Recommending','Acts with approval','Autonomous'][f.autonomy]}</b><span>{f.autonomy} of 5</span></div><input type="range" min="1" max="5" value={f.autonomy} onChange={e=>set('autonomy',+e.target.value)}/><small><i>Provides information</i><i>Acts independently</i></small></div><div className="questions"><YesNo label="Will this application be public-facing?" value={f.publicFacing} onChange={v=>set('publicFacing',v)}/></div></>}
function Impact({form:f,set}:Props){return <><Heading step={3} icon="shield" title="Impact & safeguards" sub="Help us understand the consequences of an incorrect output."/><div className="questions"><YesNo label="Could an incorrect response affect patient safety?" value={f.safety} onChange={v=>set('safety',v)}/><YesNo label="Could it affect product quality or a regulated process?" value={f.quality} onChange={v=>set('quality',v)}/><YesNo label="Could it influence a clinical, employment, or other consequential decision?" value={f.decisions} onChange={v=>set('decisions',v)}/><YesNo label="Will a person review outputs before they are acted upon?" value={f.humanReview} onChange={v=>set('humanReview',v)}/><YesNo label="Will prompts, outputs, and actions be recorded for audit?" value={f.audit} onChange={v=>set('audit',v)}/></div></>}
function Review({form:f,risk:r}:{form:Form;risk:Risk}){return <><Heading step={4} icon="check" title="Review your request" sub="Confirm the details and understand the proposed review path."/><div className="review-banner"><b className={r.level.toLowerCase()}>{r.score}</b><div><p>PRELIMINARY CLASSIFICATION</p><h3>{r.level} risk</h3><span>Reviewers make the final determination.</span></div></div><section className="summary"><h3>Application</h3><div><span>Name<strong>{f.name||'Not provided'}</strong></span><span>Business unit<strong>{f.unit||'Not provided'}</strong></span><span className="full">Business need<strong>{f.summary||'Not provided'}</strong></span></div></section><section className="summary"><h3>Proposed review path</h3><div className="route">{r.reviewers.map((x,i)=><span key={x}><b>{i+1}</b><strong>{x}</strong></span>)}</div></section><section className="summary"><h3>Why this classification?</h3><ul>{r.reasons.map(x=><li key={x}><Icon name="info"/>{x}</li>)}</ul></section><label className="attest"><input type="checkbox"/> I confirm the information provided is accurate to the best of my knowledge.</label></>}
function RiskPanel({risk:r}:{risk:Risk}){return <aside className="risk"><div className="risk-title"><i className={r.level.toLowerCase()}><Icon name="shield"/></i><div><p>LIVE RISK PROFILE</p><h3>{r.level} risk</h3></div><b className={r.level.toLowerCase()}>{r.score}/100</b></div><div className="notice"><Icon name="info"/>Preliminary classification based on your answers. This is not an approval decision.</div><section><h4>Risk dimensions</h4>{r.dimensions.map(d=><div className="dimension" key={d.name}><p><span>{d.name}</span><b>{d.value<22?'Low':d.value<50?'Moderate':'High'}</b></p><div><i className={d.value<22?'low':d.value<50?'moderate':'high'} style={{width:`${Math.max(3,d.value)}%`}}/></div></div>)}</section><section><h4>What is driving this?</h4>{r.reasons.slice(0,3).map(x=><p className="reason" key={x}><i/> {x}</p>)}</section><section><h4>Likely reviewers <Pill text={`${r.reviewers.length}`} tone="In review"/></h4><div className="reviewers">{r.reviewers.map(x=><span key={x}>{x}</span>)}</div></section>{r.controls.length>0&&<section className="controls"><h4>Recommended safeguards</h4>{r.controls.map(x=><p key={x}><Icon name="check"/>{x}</p>)}</section>}<button className="learn">How classification works <Icon name="arrow"/></button></aside>}
function Intake({exit,submit}:{exit:()=>void;submit:()=>void}){const[step,setStep]=useState(0),[saved,setSaved]=useState(false),[form,setForm]=useState<Form>(()=>{try{return JSON.parse(localStorage.getItem('ai-draft')||'null')||initial}catch{return initial}});const risk=useMemo(()=>calculate(form),[form]);const set=<K extends keyof Form>(k:K,v:Form[K])=>{setForm(f=>({...f,[k]:v}));setSaved(false)};useEffect(()=>{const t=setTimeout(()=>localStorage.setItem('ai-draft',JSON.stringify(form)),500);return()=>clearTimeout(t)},[form]);const save=()=>{localStorage.setItem('ai-draft',JSON.stringify(form));setSaved(true)};const next=()=>{if(step<4){setStep(s=>s+1);scrollTo(0,0)}else{localStorage.removeItem('ai-draft');submit()}};return <div className="intake"><div className="intake-top"><button onClick={exit}><Icon name="back"/>My applications</button><span>Draft · AI request</span><button className="secondary" onClick={save}><Icon name="save"/>{saved?'Saved':'Save draft'}</button></div><div className="stepper">{stepNames.map((x,i)=><button key={x} className={`${i===step?'active':''} ${i<step?'done':''}`} onClick={()=>i<=step&&setStep(i)}><b>{i<step?<Icon name="check"/>:`0${i+1}`}</b><span>{x}</span>{i<4&&<i/>}</button>)}</div><main className="intake-main"><div className="form-card">{step===0&&<Basics form={form} set={set}/>} {step===1&&<Data form={form} set={set}/>} {step===2&&<Capabilities form={form} set={set}/>} {step===3&&<Impact form={form} set={set}/>} {step===4&&<Review form={form} risk={risk}/>}<div className="form-actions"><button className="secondary" onClick={()=>step?setStep(s=>s-1):exit()}><Icon name="back"/>{step?'Back':'Cancel'}</button><div><span>{step+1} of 5</span><button className="primary" onClick={next}>{step===4?'Submit for review':'Continue'}<Icon name="arrow"/></button></div></div></div><RiskPanel risk={risk}/></main></div>}
function Submitted({home}:{home:()=>void}){return <main className="submitted"><div><Icon name="check"/></div><Pill text="Request submitted" tone="Approved"/><h1>Your AI application is on its way.</h1><p>Request <b>AI-2026-0157</b> has been sent for initial governance review. We’ll notify you when action is required.</p><section><span>Next step<strong>Business owner review</strong></span><span>Expected response<strong>2–3 business days</strong></span><span>Request owner<strong>Nathan Biyani</strong></span></section><button className="primary" onClick={home}>Return to my applications</button></main>}
export default function IntakeApp(){const[view,setView]=useState<View>(restoredPortalView);useEffect(()=>{try{sessionStorage.setItem(portalViewKey,view)}catch{/* Storage may be unavailable in a restricted browser context. */}},[view]);const openApprovedDeployment=async()=>{const packageId='AI-2026-0118-g-8a429b5f';const deploymentName='quality-rag-poc-f5d8cb34';const subscriptionId=import.meta.env.VITE_AZURE_SUBSCRIPTION_ID??'';sessionStorage.setItem('launchpad.active-deployment',JSON.stringify({packageId,deploymentName,subscriptionId}));try{const pkg=await getBicepPackage(packageId);sessionStorage.setItem('launchpad.generated-package',JSON.stringify(pkg));sessionStorage.setItem('launchpad.workspace-screen','iac')}catch(error){console.error('Approved deployment package could not be restored.',error);sessionStorage.removeItem('launchpad.generated-package');sessionStorage.setItem('launchpad.workspace-screen','overview')}finally{setView('solution')}};return <><Header home={()=>setView('dashboard')} council={()=>setView('council')} active={view==='council'?'council':'developer'}/>{view==='dashboard'&&<ConfigurationDashboard start={()=>setView('intake')} configure={openApprovedDeployment}/>} {view==='intake'&&<Intake exit={()=>setView('dashboard')} submit={()=>setView('submitted')}/>} {view==='submitted'&&<Submitted home={()=>setView('dashboard')}/>} {view==='solution'&&<SolutionBuilder exit={()=>setView('dashboard')}/>} {view==='council'&&<CouncilWorkspace/>}</>}
